

server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
  datasource:
    username: admin
    password: 123456@
    url: jdbc:h2:mem:elasticdb
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
