version: '3.8'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.1.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
    ports:
      - "9200:9200"
    deploy:
      resources:
        limits:
          memory: 2g
    volumes:
      - es-data:/usr/share/elasticsearch/data
    networks:
      - es-net
  kibana:
    image: docker.elastic.co/kibana/kibana:8.1.2
    container_name: kibana
    depends_on:
      - elasticsearch
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - 5601:5601
    volumes:
      - kibana-data:/usr/share/kibana/data
    networks:
      - es-net
networks:
  es-net:

volumes:
  es-data:
  kibana-data:
